### ISSUE TITLE
Pyffi : Regression Kfm reader broken

### ISSUE THREAD

**Issue by neomonkeus** [niftools/pyffi#40]
@niftools/pyffi-reviewers

## Issue Overview 
The kfm toaster is unable to read kfm files

### Pyffi Version Info
2.2.3

### Platform information
win32

## Context
DocString tests are failing when executed related to kfm support
 - kfmtoaster.txt 

## Steps to Reproduce
 #. Update test_doctest.py to include the above doctest paths
 #. py.test -v /tests/test_doctests.py

## Expected Result
Test should pass without failure

## Actual Result
Tests should be able to read the file, but it appears that some functionality is not implemented.
It could also be that there is some inheritance issue.

## Possible Fix
It might not be using the concrete implementation, but the base Toaster Object.

## Screenshot
N\A
## Logs and Files
N\A

### Console Output
```
File ".\pyffi\tests\formats\kfm\kfmtoaster.txt", line 35, in kfmtoaster.txt
Failed example:
    kfmtoaster.KfmToaster().cli() # doctest: +ELLIPSIS
Exception raised:
    Traceback (most recent call last):
      File "C:\Python34\Lib\doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest kfmtoaster.txt[17]>", line 1, in <module>
        kfmtoaster.KfmToaster().cli() # doctest: +ELLIPSIS
      File ".\pyffi\pyffi\spells\__init__.py", line 1265, in cli
        self.toast(self.top)
      File ".\pyffi\pyffi\spells\__init__.py", line 1381, in toast
        self._toast(stream)
      File ".\pyffi\pyffi\spells\__init__.py", line 1453, in _toast
        data.inspect(stream)
      File ".\pyffi\pyffi\object_models\__init__.py", line 195, in inspect
        raise NotImplementedError
    NotImplementedError
----------------------------------------------------------------------
File ".\pyffi\tests\formats\kfm\kfmtoaster.txt", line 42, in kfmtoaster.txt
Failed example:
    kfmtoaster.KfmToaster().cli() # doctest: +ELLIPSIS
Exception raised:
    Traceback (most recent call last):
      File "C:\Python34\Lib\doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest kfmtoaster.txt[19]>", line 1, in <module>
        kfmtoaster.KfmToaster().cli() # doctest: +ELLIPSIS
      File ".\pyffi\pyffi\spells\__init__.py", line 1265, in cli
        self.toast(self.top)
      File ".\pyffi\pyffi\spells\__init__.py", line 1381, in toast
        self._toast(stream)
      File ".\pyffi\pyffi\spells\__init__.py", line 1453, in _toast
        data.inspect(stream)
      File ".\pyffi\pyffi\object_models\__init__.py", line 195, in inspect
        raise NotImplementedError
    NotImplementedError
----------------------------------------------------------------------
File ".\pyffi\tests\formats\kfm\kfmtoaster.txt", line 52, in kfmtoaster.txt
Failed example:
    kfmtoaster.KfmToaster().cli() # doctest: +ELLIPSIS +REPORT_UDIFF
Exception raised:
    Traceback (most recent call last):
      File "C:\Python34\Lib\doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest kfmtoaster.txt[21]>", line 1, in <module>
        kfmtoaster.KfmToaster().cli() # doctest: +ELLIPSIS +REPORT_UDIFF
      File ".\pyffi\pyffi\spells\__init__.py", line 1265, in cli
        self.toast(self.top)
      File ".\pyffi\pyffi\spells\__init__.py", line 1381, in toast
        self._toast(stream)
      File ".\pyffi\pyffi\spells\__init__.py", line 1453, in _toast
        data.inspect(stream)
      File ".\pyffi\pyffi\object_models\__init__.py", line 195, in inspect
        raise NotImplementedError
    NotImplementedError

```

## Similar Known Issues
N\A

## Additional Information
N\A

**Comment by TagnumElite** [comment]
When [this commit](https://github.com/niftools/pyffi/commit/392c75ef387111e4ee3c68b5d663582003e897e3#diff-1fed831dc9840d4e44d988c690081400) happened, the KfmFormat was never updated, I am busy in the process of fixing this.

**Comment by neomonkeus** [comment]
Yeah, decided to forego fixing this at the time as the changes in the general PR were more priority, but created this ticket to track to ensure it wasn't lost.
